blank_issues_enabled: false
contact_links:
  - name: I've got an idea for something to add to Universal Notifier 
    url: https://github.com/jumping2000/universal_notifier/discussions/categories/ideas
    about: Please use our dicussion form to share your ideas.
  - name: I have a question or need support
    url: https://github.com/jumping2000/universal_notifier/discussions
    about: Please use our discussion forums for getting help in that case.
  - name: I'm unsure where to go
    url: https://github.com/jumping2000/universal_notifier/
    about: Check out documentation for more details and guidance in that case.
